pipeline:
  name: shreyanshGupta
  identifier: shreyanshGupta
  projectIdentifier: shreyansh_Practice
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        repoName: org.NodeGoat
        build: <+input>
  stages:
    - stage:
        name: Security
        identifier: Security
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Gitleaks
                  name: Gitleaks_1
                  identifier: Gitleaks_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
